### ISSUE TITLE
Lesson 1 - "mdi icons" don't seem to work

### ISSUE THREAD

**Issue by stlsmiths** [Code-Pop/beautify-with-vuetify#13]
I just started this course and Lesson 1 I found that the `prepend-icon="mdi-account-circle"` and others did not render properly, got the default "squares".  I am using the current veutify: ^2.2.11 in package.json per the install.  

After some perusing of the [Veutify Docs](https://vuetifyjs.com/en/customization/icons/#icons) they state that the npm package "@mdi/font" is required and that the import needs to be added to the `veutify.js` file.  I did this and it seems to render properly now.

Not sure if I did something wrong along the way, but thought I'd mention this.

**Comment by bencodezen** [comment]
So I've tested this two different ways:

1. Checked out `Lesson-1-BEGIN` branch on this repo. And then ran `vue add vuetify` and it seems to work.
2. Create a new project with Vue CLI `vue create vuetify-experiment` and then ran `vue add vuetify`

Do you have a repo that I could reproduce this?

**Comment by stlsmiths** [comment]
Hi @bencodezen - 
I have a my working repo with this commit https://github.com/stlsmiths/veutify-dashboard/commit/0a841d556d5573459cd4b1245a4fe7a0ff094ded.  

I am running Vue cli 4.4.6. 

Since I'm new to Vue I probably munged something.
 1. I started project with `vue create`
 2. I added veutify with `vue add veutify` ... which added ^2.2.11

When I followed lesson 1, I did not get the icons ... so went to docs and found the "@mdi/font"  I referenced earlier.

If it worked for you - no worries, I can try to create a new project.

... For now, I am busy enjoying and completing your class on this! 
Cheers and thanks for the project!

**Comment by stlsmiths** [comment]
@bencodezen  I fired up a new project using the steps 1-2 from above and added 

``` <v-text-field label="username" prepend-icon="mdi-account-circle" />```

 and it renders properly with the correct icon.  

As I expected - it must have been my error all along.  Sorry for the distraction!

So I'll close this issue 👍🏼

**Comment by bencodezen** [comment]
No worries. Glad it's working @stlsmiths!
